# Generated by Django 5.0.14 on 2025-12-26 15:30

import django.db.models.deletion
import django.utils.timezone
import lobby.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=lobby.models.generate_room_code, editable=False, max_length=8, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=20)),
                ('session_key', models.CharField(max_length=40)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='lobby.room')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('room', 'icon'), ('room', 'nickname')},
            },
        ),
    ]
