# Generated by Django 5.0.14 on 2025-12-27 14:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_room_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('storia', 'Storia'), ('scienza', 'Scienza'), ('cultura', 'Cultura generale'), ('sport', 'Sport'), ('geografia', 'Geografia')], max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Livello 1'), (2, 'Livello 2'), (3, 'Livello 3'), (4, 'Livello 4'), (5, 'Livello 5')])),
                ('text', models.TextField(verbose_name='Domanda')),
                ('option_a', models.CharField(max_length=255, verbose_name='Opzione A')),
                ('option_b', models.CharField(max_length=255, verbose_name='Opzione B')),
                ('option_c', models.CharField(max_length=255, verbose_name='Opzione C')),
                ('correct_option', models.CharField(choices=[('A', 'Opzione A'), ('B', 'Opzione B'), ('C', 'Opzione C')], max_length=1)),
                ('is_active', models.BooleanField(default=True, help_text='Disattiva per escludere la domanda dai quiz.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['category', 'difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('choosing', 'Scelta categoria/livello'), ('answering', 'Domanda attiva'), ('finished', 'Finita')], default='choosing', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_games', to='lobby.player')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='lobby.room')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='lobby.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_entries', to='lobby.player')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GameTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('selected_option', models.CharField(blank=True, choices=[('A', 'Opzione A'), ('B', 'Opzione B'), ('C', 'Opzione C')], max_length=1, null=True)),
                ('was_correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='lobby.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='lobby.player')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='current_turn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_game', to='lobby.gameturn'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(('difficulty__gte', 1), ('difficulty__lte', 5)), name='question_level_between_1_5'),
        ),
        migrations.AddField(
            model_name='gameturn',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='lobby.question'),
        ),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('game', 'player')},
        ),
        migrations.AddConstraint(
            model_name='gameturn',
            constraint=models.UniqueConstraint(fields=('game', 'question'), name='unique_question_per_game'),
        ),
    ]
