# Generated by Django 5.0.14 on 2025-12-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_question_game_gameplayer_gameturn_game_current_turn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_questions', to='lobby.game')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_questions', to='lobby.question')),
            ],
            options={
                'unique_together': {('game', 'question')},
            },
        ),
    ]
